#!/bin/bash

. /etc/default/openmanage

PID=/var/run/gunicorn_console.pid

SOCK=unix:$OPENMANAGE_DATA/admin_console.sock

if [ -f $PID ]; then rm $PID; fi

cd $OPENMANAGE_DJANGO_ROOT/omva
exec gunicorn_django -b $SOCK --pid=$PID
