#!/bin/bash

. /etc/default/openmanage

source /home/openmanage/.virtualenvs/omva/bin/activate

PID=/var/run/gunicorn_console.pid

SOCK=unix:$OPENMANAGE_DATA/admin_console.sock

if [ -f $PID ]; then rm $PID; fi

cd $OPENMANAGE_DJANGO_ROOT/omva
exec gunicorn --timeout 300 --log-level=DEBUG -b $SOCK -w 10 --pid=$PID omva.wsgi:application 2>&1
