language: python
python:
  - "2.7"
addons:
  apt:
    packages:
      - libffi-dev
      - python-psycopg2 
      - python-crypto 
      - python-ldap 
      - python-cerealizer
      - python-dev 
      - libldap2-dev 
      - libsasl2-dev 
      - libssl-dev
before_install:
  - wget https://bootstrap.pypa.io/ez_setup.py -O - | sudo python
install:
  - pip install setuptools --upgrade
  - pip install pip==9.0.1
  - pip install -r upgrade/requirements.txt
  - pip install cffi --upgrade
  - pip install mock --upgrade
  - pip install six --upgrade
  - pip install pycparser==2.10
  - pip install cerealizer
  - pip install psycopg2
  - pip install python-ldap
script:
  - pip freeze
  - python -c "import cerealizer; print cerealizer.VERSION"
  - python test_netkes_client.py
  - make test_netkes
