language: python
python:
  - "2.7"
addons:
  apt:
    packages:
      - libffi-dev
      - python-psycopg2 
      - python-crypto 
      - python-ldap 
      - python-cerealizer
      - python-dev 
      - libldap2-dev 
      - libsasl2-dev 
      - libssl-dev
before_install:
  - wget https://bootstrap.pypa.io/ez_setup.py -O - | sudo python
install:
  - pip install setuptools --upgrade
  - pip install pip==9.0.1
  - pip install Django==1.8.17
  - pip install pytz==2016.10
  - pip install py-bcrypt==0.4
  - pip install pycrypto==2.6.1
  - pip install pynacl==1.1.1
  - pip install inflection==0.3.1
  - pip install cffi --upgrade
  - pip install mock --upgrade
  - pip install six --upgrade
  - pip install pycparser==2.10
    #  - pip install cerealizer==0.6
  - pip install requests
  - pip install psycopg2
  - pip install python-ldap
script:
  - python test_netkes_client.py
  - make test_netkes
