language: python
python:
  - "2.7"
install:
  - apt-get install libffi-dev
  - pip install pip==1.4.1
  - pip install Django==1.5.10
  - pip install pytz==2013.8
  - pip install py-bcrypt==0.4
  - pip install pycrypto==2.4.1
  - pip install cffi==0.8.2
  - pip install six==1.6.1
  - pip install pycparser==2.10
  - pip install pynacl==0.2.3
script:
  - python test_netkes_client.py
