language: python
python:
  - "2.7"
addons:
  apt:
    packages:
      - libffi-dev
      - python-psycopg2 
      - python-crypto 
      - python-ldap 
      - python-cerealizer
      - python-dev 
      - libldap2-dev 
      - libsasl2-dev 
      - libssl-dev
virtualenv:
  system_site_packages: true
before_install:
  - wget https://bootstrap.pypa.io/ez_setup.py -O - | sudo python
install:
  - pip install -r upgrade/requirements.txt
  - pip install pycparser==2.17
script:
  - python test_netkes_client.py
  - make test_travis_ci
