# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-11 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blue_mgnt', '0003_invoicenote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicenote',
            name='note',
            field=models.TextField(default=b'', help_text=b'An optional note that will appear on your invoices. Use this if you need to add an address, VAT number, or similar.'),
        ),
    ]
